apiVersion: v1
kind: Deployment
metadata:
  name: test-deployment


spec:
  replicas: 2
  selectors:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: test-container
          image: nginx
          ports:
            - containerPort: 80
